# GitHub Actions Documentation: https://docs.github.com/en/actions
name: "Continuous Integration"

on:
    push:
        branches:
            - "main"
        tags:
            - "*"
    pull_request:
        branches:
            - "main"

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name.
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    coding-standards:
        name: "Coding standards"
        runs-on: "ubuntu-latest"
        
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v5"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "latest"
                  coverage: "none"

            - name: "Install dependencies (Composer)"
              uses: "ramsey/composer-install@v3"

            - name: "Check code style"
              run: "vendor/bin/phpcs"
    
    static-analysis:
        name: "Static analysis"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v5"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "latest"
                  coverage: "none"

            - name: "Install dependencies (Composer)"
              uses: "ramsey/composer-install@v3"

            - name: "Statically analyze code (PHPStan)"
              run: "vendor/bin/phpstan"
    
    unit-tests:
        name: "Unit tests"
        runs-on: ${{ matrix.os }}
        
        strategy:
            fail-fast: false
            matrix:
                php:
                    - "8.3"
                    - "8.4"
                    - "8.5"
                os:
                    - "macos-latest"
                    - "ubuntu-latest"
                    - "windows-latest"
                composer-deps:
                    - "lowest"
                    - "highest"
        
        steps:
            - name: "Configure Git (for Windows)"
              if: ${{ matrix.os == 'windows-latest' }}
              shell: "bash"
              run: |
                  git config --system core.autocrlf false
                  git config --system core.eol lf

            - name: "Checkout repository"
              uses: "actions/checkout@v5"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php }}"
                  coverage: "none"

            - name: "Install dependencies (Composer)"
              uses: "ramsey/composer-install@v3"
              with:
                  dependency-versions: "${{ matrix.composer-deps }}"

            - name: "Run unit tests (PHPUnit)"
              shell: "bash"
              run: "vendor/bin/phpunit"
